import {useEffect,useMemo,useState} from 'react'
import {AnimatePresence,motion} from 'framer-motion'
import QRCode from 'qrcode'
import {Link,Type,Wifi,MessageCircle,Contact,Mail,MessageSquare,Phone,MapPin,CalendarDays,Github,Moon,Sun,SlidersHorizontal,Palette,Download,FileCode2,Copy,ShieldCheck,Sparkles,ChevronDown} from 'lucide-react'
import type {Fields,QROptions,QRType} from './types'
import {buildPayload} from './utils/qrPayloads'
import {validate} from './utils/validation'
import {presets} from './utils/themePresets'
import {downloadPNG,downloadSVG} from './utils/qrDownload'
import {AnimatedBackground} from './components/AnimatedBackground'
import {AppLayout} from './components/AppLayout'
import {QRTypeCard} from './components/QRTypeCard'
import {FieldGroup,TextInput,TextArea,SelectInput,ColorInput,RangeInput} from './components/Inputs'
import {ThemePresetSelector} from './components/ThemePresetSelector'
import {QRPreview} from './components/QRPreview'
import {PhonePreview} from './components/PhonePreview'
import {DownloadButton,CopyButton} from './components/Buttons'
import {Toast} from './components/Toast'
import {ErrorMessage} from './components/ErrorMessage'

const types=[['url','URL',Link],['text','Text',Type],['wifi','WiFi',Wifi],['whatsapp','WhatsApp',MessageCircle],['vcard','vCard',Contact],['email','Email',Mail],['sms','SMS',MessageSquare],['phone','Phone',Phone],['location','Location',MapPin],['event','Event',CalendarDays]] as const
const defaults:Record<QRType,Fields>={url:{url:'https://github.com/rayyanzoffice-ux/qr-code-toolkit'},text:{text:'Create something remarkable.'},wifi:{ssid:'Studio WiFi',password:'',security:'WPA',hidden:false},whatsapp:{country:'+1',phone:'',message:'Hello!'},vcard:{name:'',organization:'',job:'',phone:'',email:'',website:'',address:''},email:{email:'',subject:'',body:''},sms:{phone:'',message:''},phone:{phone:''},location:{latitude:'',longitude:'',label:''},event:{title:'',location:'',start:'',end:'',description:''}}
const fieldMap:Record<QRType,Array<{key:string;label:string;kind?:string;placeholder?:string;required?:boolean;options?:string[]}>>={
 url:[{key:'url',label:'Website URL',placeholder:'https://example.com',required:true}],text:[{key:'text',label:'Your text',kind:'area',placeholder:'Type anything…',required:true}],wifi:[{key:'ssid',label:'Network name (SSID)',required:true},{key:'password',label:'Password',kind:'password'},{key:'security',label:'Security',kind:'select',options:['WPA','WEP','nopass']}],whatsapp:[{key:'country',label:'Country code',placeholder:'+1'},{key:'phone',label:'Phone number',required:true},{key:'message',label:'Message',kind:'area'}],vcard:[{key:'name',label:'Full name',required:true},{key:'organization',label:'Organization'},{key:'job',label:'Job title'},{key:'phone',label:'Phone'},{key:'email',label:'Email',kind:'email'},{key:'website',label:'Website'},{key:'address',label:'Address',kind:'area'}],email:[{key:'email',label:'Email address',kind:'email',required:true},{key:'subject',label:'Subject'},{key:'body',label:'Body',kind:'area'}],sms:[{key:'phone',label:'Phone number',required:true},{key:'message',label:'Message',kind:'area'}],phone:[{key:'phone',label:'Phone number',required:true}],location:[{key:'latitude',label:'Latitude',required:true},{key:'longitude',label:'Longitude',required:true},{key:'label',label:'Optional label'}],event:[{key:'title',label:'Event title',required:true},{key:'location',label:'Location'},{key:'start',label:'Start date & time',kind:'datetime-local',required:true},{key:'end',label:'End date & time',kind:'datetime-local',required:true},{key:'description',label:'Description',kind:'area'}]}
export default function App(){const [type,setType]=useState<QRType>('url');const [allFields,setAllFields]=useState(defaults);const [options,setOptions]=useState<QROptions>({foreground:'#cbff5e',background:'#07120f',accent:'#4dfbd2',size:512,margin:3,level:'M',pattern:'dots'});const [preset,setPreset]=useState('Neon');const [dark,setDark]=useState(true);const [toast,setToast]=useState('');const [phoneImage,setPhoneImage]=useState('');const fields=allFields[type];const payload=useMemo(()=>buildPayload(type,fields),[type,fields]);const error=useMemo(()=>validate(type,fields),[type,fields]);
 useEffect(()=>{if(error||!payload)return;let live=true;QRCode.toDataURL(payload,{width:180,margin:options.margin,errorCorrectionLevel:options.level,color:{dark:options.foreground,light:options.background}}).then(x=>live&&setPhoneImage(x));return()=>{live=false}},[payload,error,options]);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(''),2200)};const update=(key:string,value:string|boolean)=>setAllFields(v=>({...v,[type]:{...v[type],[key]:value}}));const applyPreset=(name:string)=>{setPreset(name);setOptions(o=>({...o,...presets[name]}))};const download=async(kind:'PNG'|'SVG')=>{if(error)return;if(kind==='PNG')await downloadPNG(payload,options);else await downloadSVG(payload,options);notify(`${kind} downloaded successfully`)}
 const left=<><div className="panel-title"><span>QR TYPE</span><small>10 FORMATS</small></div><div className="type-grid">{types.map(([id,label,icon])=><QRTypeCard key={id} label={label} icon={icon} active={type===id} onClick={()=>setType(id)}/>)}</div><div className="privacy"><ShieldCheck/><div><b>100% private</b><small>Your data never leaves this device.</small></div></div></>
 const center=<><div className="section-heading"><div className="title-icon">{(()=>{const I=types.find(x=>x[0]===type)![2];return <I/>})()}</div><div><span>CREATE</span><h1>{types.find(x=>x[0]===type)?.[1]} QR Code</h1></div></div><AnimatePresence mode="wait"><motion.div className="fields-grid" key={type} initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}}>{fieldMap[type].map(f=><FieldGroup key={f.key} label={f.label} required={f.required}>{f.kind==='area'?<TextArea value={String(fields[f.key]||'')} placeholder={f.placeholder} onChange={e=>update(f.key,e.target.value)}/>:f.kind==='select'?<SelectInput value={String(fields[f.key])} onChange={e=>update(f.key,e.target.value)}>{f.options?.map(x=><option key={x} value={x}>{x==='nopass'?'None':x==='WPA'?'WPA / WPA2':x}</option>)}</SelectInput>:<TextInput type={f.kind||'text'} value={String(fields[f.key]||'')} placeholder={f.placeholder} onChange={e=>update(f.key,e.target.value)}/>}</FieldGroup>)}{type==='wifi'&&<label className="toggle-row"><input type="checkbox" checked={Boolean(fields.hidden)} onChange={e=>update('hidden',e.target.checked)}/><span/>Hidden network</label>}</motion.div></AnimatePresence>{error&&<ErrorMessage message={error}/>}<div className="divider"/><div className="subhead"><Palette/> Style & color</div><ThemePresetSelector active={preset} onSelect={applyPreset}/><div className="option-grid"><FieldGroup label="Foreground"><ColorInput value={options.foreground} onChange={foreground=>setOptions(o=>({...o,foreground}))}/></FieldGroup><FieldGroup label="Background"><ColorInput value={options.background} onChange={background=>setOptions(o=>({...o,background}))}/></FieldGroup><FieldGroup label="Accent / glow"><ColorInput value={options.accent} onChange={accent=>setOptions(o=>({...o,accent}))}/></FieldGroup></div><FieldGroup label="Pattern style"><div className="segments">{(['square','rounded','dots'] as const).map(p=><button className={options.pattern===p?'active':''} onClick={()=>setOptions(o=>({...o,pattern:p}))} key={p}>{p}</button>)}</div></FieldGroup><div className="divider"/><div className="subhead"><SlidersHorizontal/> Advanced options</div><div className="slider"><span>QR size <b>{options.size}px</b></span><RangeInput min={256} max={1024} value={options.size} onChange={size=>setOptions(o=>({...o,size}))}/></div><div className="slider"><span>Quiet zone <b>{options.margin}</b></span><RangeInput min={0} max={8} value={options.margin} onChange={margin=>setOptions(o=>({...o,margin}))}/></div><FieldGroup label="Error correction"><SelectInput value={options.level} onChange={e=>setOptions(o=>({...o,level:e.target.value as QROptions['level']}))}>{['L','M','Q','H'].map(x=><option key={x}>{x}</option>)}</SelectInput></FieldGroup></>
 const right=<><div className="preview-head"><div><span>LIVE PREVIEW</span><b><i/> Ready to scan</b></div><button aria-label="Preview menu"><ChevronDown/></button></div><QRPreview payload={payload} options={options} error={error}/><div className="device-row"><PhonePreview canvasSource={error?'':phoneImage} accent={options.accent}/><div className="device-copy"><span>DEVICE PREVIEW</span><h3>Looks great<br/>everywhere.</h3><p>Optimized for instant scanning on any modern device.</p><div><i/><i/><i/></div></div></div><div className="payload"><div><span>PAYLOAD</span><small>{payload.length} CHARACTERS</small></div><pre>{payload||'Waiting for your input…'}</pre></div><div className="actions"><DownloadButton icon={Download} label="Download PNG" onClick={()=>download('PNG')}/><DownloadButton icon={FileCode2} label="SVG" onClick={()=>download('SVG')}/><CopyButton icon={Copy} onClick={()=>navigator.clipboard.writeText(payload).then(()=>notify('Payload copied to clipboard'))}/></div></>
 return <><AnimatedBackground/><AppLayout header={<><a className="brand" href="/"><span><Sparkles/></span><div><b>QR Code</b> Toolkit<small>CREATE • CUSTOMIZE • SHARE</small></div></a><div className="header-actions"><a href="https://github.com/rayyanzoffice-ux/qr-code-toolkit" target="_blank" rel="noreferrer"><Github/> <span>GitHub</span></a><button aria-label="Toggle color theme" onClick={()=>setDark(x=>!x)}>{dark?<Sun/>:<Moon/>}</button></div></>} left={left} center={center} right={right}/><Toast message={toast}/></>}
